/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TicketsObjectPageObjectPage journey");

        opaTest("Navigate to TicketsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheTicketsList.onFilterBar().iExecuteSearch();

            Then.onTheTicketsList.onTable().iCheckRows();
            When.onTheTicketsList.onTable().iPressRow(0);

            Then.onTheTicketsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTicketsObjectPage.iCheckNumberOfSections(3);
            When.onTheTicketsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::TicketDetails");
            Then.onTheTicketsObjectPage.iCheckSection({ section: "FieldGroup::TicketDetails" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "ticketNo" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "title" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "description" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "priority" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "status" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "source" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "dueDate" });
            Then.onTheTicketsObjectPage.onForm({ section: "FieldGroup::TicketDetails" }).iCheckField({ property: "resolvedAt" });
            When.onTheTicketsObjectPage.iPressSectionIconTabFilterButton("comments::LineItem");
            Then.onTheTicketsObjectPage.iCheckSection({ section: "comments::LineItem" });
            When.onTheTicketsObjectPage.iPressSectionIconTabFilterButton("aiRecommendations::LineItem");
            Then.onTheTicketsObjectPage.iCheckSection({ section: "aiRecommendations::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});