/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TicketsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheTicketsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheTicketsList.onFilterBar().iCheckFilterField("ticketNo");
            Then.onTheTicketsList.onFilterBar().iCheckFilterField("priority");
            Then.onTheTicketsList.onFilterBar().iCheckFilterField("status");
            Then.onTheTicketsList.onFilterBar().iCheckFilterField("source");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheTicketsList.onTable().iCheckColumns(undefined, {"ticketNo":{"header":"Ticket No"},"title":{"header":"Title"},"priority":{"header":"Priority"},"status":{"header":"Status"},"source":{"header":"Source"},"dueDate":{"header":"Due Date"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheTicketsList.onFilterBar().iExecuteSearch();
            
            Then.onTheTicketsList.onTable().iCheckRows();

            When.onTheTicketsList.onTable().iPressRow(0);
            Then.onTheTicketsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});